### ISSUE TITLE
Adopt the Workspace Trust feature which arrives in VS Code 1.57

### ISSUE THREAD

**Issue by gjsjohnmurray** [george-james-software/gjLocate#1]
As soon as VS Code 1.57 lands (due later this week) extensions will be disabled by default in untrusted workspaces, and every workspace will default to being untrusted until the user marks it as trusted.

See https://code.visualstudio.com/docs/editor/workspace-trust and https://github.com/microsoft/vscode/issues/120251

AFAIK this extension doesn't implement any features that require trust, in which case we should add the follow to its `package.json`

```
	"capabilities": {
		"untrustedWorkspaces": {
			"supported": true
		}
	},
```

**Comment by george-james-software** [comment]
Done in 1.1.0
